language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
before_install:
  - if [[ $TRAVIS_PYTHON_VERSION == '3.2' ]]; then pip install 'coverage<4.0.0'; fi
  - pip install coveralls
install:
  - pip install -r requirements.txt
  - cp misc/config.sample.py config.py
script: 
  - py.test --cov=app/ --cov-report=term-missing
after_success:
  - coveralls
